[blutgang]
# Clear the cache DB on startup
do_clear = false
# Where to bind blutgang to
address = "0.0.0.0:3000"
# Moving average length for the latency
ma_length = 100
# Sort RPCs by latency on startup. Recommended to leave on.
sort_on_startup = true
# Enable health checking
health_check = true
# Acceptable time to wait for a response in ms
ttl = 3_000
# How many times to retry a request before giving up
max_retries = 3
# Time between health checks in ms
health_check_ttl = 120_000


# Note: the admin namespace contains volatile functions and
# should not be exposed publicly.
[admin]
# Enable the admin namespace
enabled = false
# Address for the admin RPC
address = "0.0.0.0:5715"
# Only allow read-only methods
# Recommended `true` unless you 100% need write methods
readonly = true
# Enable JWT request authentication
# MUST BE ENABLED IN PROD
jwt = false
# JWT token
key = "some-token-replace-this"

# Sled config
# Sled is the database we use for our cache, for more info check their docs
[sled]
# Path to db
db_path = "/db"
# sled mode. Can be HighThroughput/LowSpace
mode = "LowSpace"
# Cache size in bytes.
cache_capacity = 1_000_000_000
# Use zstd compression. Reduces size 60-70%,
# and increases CPU and latency by around 10% for db writes and 2% for reads.
# If storage constrained, it's fine to have it be on.
compression = true
# Print DB profile when dropped. Doesn't do anything for now.
print_profile = false
# Frequency of flushes in ms
flush_every_ms = 24_000

url = "https://arbitrum.llamarpc.com" # RPC url
max_consecutive = 150_000             # The maximum amount of time we can use this RPC in a row.
max_per_second = 1                    # Max ammount of queries per second. Note: Does nothing ATM

[ankr]
url = "https://rpc.ankr.com/arbitrum"
max_consecutive = 150_000
max_per_second = 1

[1rpc]
url = "https://1rpc.io/arb"
max_consecutive = 150_000
max_per_second = 1
